### ISSUE TITLE
如何评估KITTI测试结果

### ISSUE THREAD

**Issue by 1usabak** [YJLCV/Guard-Net#1]
请问作者，如何评估在KITTI上的测试结果呢？请问是使用代码里给出的save_disp_sceneflow.py吗？

**Comment by YJLCV** [comment]
save_disp_sceneflow.py是保存sceneflow数据集的测试结果，保存KITTI的代码我现在上传下，稍等你刷新看看

**Comment by 1usabak** [comment]
没想到会这么快收到您的邮件回复，万分感谢！！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YJLCV/Guard-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YJLCV/Guard-Net] 如何评估KITTI测试结果 (Issue #1)





 
save_disp_sceneflow.py是保存sceneflow数据集的测试结果，保存KITTI的代码我现在上传下，稍等你刷新看看

**Comment by asd9697** [comment]
> 没想到会这么快收到您的邮件回复，万分感谢！！！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "YJLCV/Guard-Net" ***@***.***&gt;; 发送时间:&nbsp;2024年5月29日(星期三) 下午4:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [YJLCV/Guard-Net] 如何评估KITTI测试结果 (Issue #1) save_disp_sceneflow.py是保存sceneflow数据集的测试结果，保存KITTI的代码我现在上传下，稍等你刷新看看 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

同学，请问你测试的epe达到作者的0.47了吗？谢谢！
