### ISSUE TITLE
kitti评估问题

### ISSUE THREAD

**Issue by fangzhou1111** [YJLCV/Guard-Net#2]
请问一下，这个算法是如何在kitti数据集上评估的？我想把自己的算法在kitti上评估，但是没有找到方法，请问可以教我一下吗，这个提交的zip是怎么存放文件再提交的
<img width="1106" alt="7eaa3e537acee97c4a875b3a27aeb77" src="https://github.com/YJLCV/Guard-Net/assets/114645948/45b7e574-8f3c-4143-8068-b150a476b979">

**Comment by YJLCV** [comment]
我有点忘了，你看下是不是：
KITTI2012提交：直接压缩成文件夹，命名无所谓；
KITTI2015提交：创建两个文件夹：disp_0放结果，flow空的就行，然后外面再套一个文件夹压缩提交

**Comment by fangzhou1111** [comment]
结果就是生成的200张png格式地视差图对吗？真的非常非常感谢您！谢谢大佬！

**Comment by YJLCV** [comment]
是的，就是[save_disp.py](https://github.com/YJLCV/Guard-Net/blob/master/save_disp.py)保存的结果

**Comment by fangzhou1111** [comment]
我说怎么提交失败了，非常感谢！！！！！

**Comment by asd9697** [comment]
> 我说怎么提交失败了，非常感谢！！！！！

同学，请问你测试的epe达到0.47 作者的指标了吗？谢谢
